version: '3'

 

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/media
    depends_on:
      - db
    volumes:
      - ./:/RickeyMorty
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=media
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - .env